### ISSUE TITLE
MultiPlayer Example did not show the 2nd player in GAMA

### ISSUE THREAD

**Issue by hqnghi88** [project-SIMPLE/simple.toolchain#6]
Using the template: Multiplayer Game\Main Scene, with the model RaceVR from LinkToUnity plugin, the first player who connected to middleware is well display in GAMA simulation. But the 2nd, even the middleware has show that player added, but there seems no conversation to GAMA,as the init block of unity_player was not trigger 2nd time. I try with latest code from simple.toolchain (template and gama plugin), the middleware is currently a mesh so i am not sure where is the cause.

**Comment by ptaillandier** [comment]
@hqnghi88  How do you run the model/game?
I tested with the latest version of the toolchain (both GAMA plugin and Unity Template) and the "Leon" release version of the middleware, and it works well.

First of all, you have in the GAMA model (Multi player game.gaml) to define the number of player (the variable "number_players" of Unity_linker). In my test, I set it to 2.
 Then, run the "vr_xp" experiment, launch the Unity application for the two players, then in the middleware (where you should see the 2 players in orange), click on "Add everyone to GAMA". And it should work.

**Comment by hqnghi88** [comment]
Thanks, i will redo witb Leon version, for model and unity, i tested with latest examples on github.

**Comment by hqnghi88** [comment]
Hi, I tried with commit eaa974d (which is released as Leon version) with 2 gama model  demo/Multi/RaceVR and CodeExample/Multi player. They both have:
- GAMA recognize 2 connected players:
id -: 'Player_7'
id -: 'Player_255'
- MdlWare had successfully add everyone to GAMA
- 1st connected player can update it heading/rotate and unity show the walls
Issue:
- 2nd connected player seems have no communication as it is still in middle of the sky and no display in GAMA.
![Image](https://github.com/user-attachments/assets/f1cfae46-1df2-4762-a959-b310063fb0f8)

**Comment by ptaillandier** [comment]
I was not testing the same model as you. I will test it

**Comment by ptaillandier** [comment]
I think, you did not run the same model in GAMA and Unity.
You should test either:
 - GAMA: Models/Code Examples/Multi player game.gaml ----- Unity: Scenes/Code Examples/Multi-player
 - GAMA: Model/Demo/Multi Player Game/RaceVR.gmal ------ Unity: Scene/Multi Player Game/Main Scene

In both case, be sure for the connection manager to set the right IP and check "Fixed Properties"

Both models/games work on my computer

**Comment by RoiArthurB** [comment]
@ptaillandier @hqnghi88 is this issue fixed ? :)

**Comment by hqnghi88** [comment]
I close this as I can have the multiplayer now (not sure when or how it is fixed or it's even not an issue) :)
